import './globals.css'
import type { Metadata } from 'next'
import { Inter,Roboto } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

  const roboto =Roboto({
    subsets:['latin'],
    display:'swap',
    weight: ["100","300","400","500","700","900"],
  })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css"  rel="stylesheet" />
      </head>
      <body className={`${inter.className}+bg-white`}>
        {children}
      <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
      </body>
    </html>
  )
}
